### PR TITLE
Adding sections to file

### PR DESCRIPTION
**Pull request by fjgomez96**
#[1]

### CODE REVIEW

**Comment by lindsayplatt** [comment]
@fjgomez96 I believe @abnerbog will be your course contact and reviewer!

**Review by abnerbog — CHANGES_REQUESTED** [review]
@fjgomez96 This is close ! There are a couple additional links you need to add in the `Getting Water to Your Homes` section then you are ready to move on.

**Review by abnerbog — APPROVED** [review]
You're all set to move on to the next step!

**Comment by fjgomez96** [comment]
Hi @abnerbog, I just finished step 9 where I closed the loop between the main repo and my local copy!

**Comment by abnerbog** [comment]
Thanks for the heads up Francisco -- you are good to keep moving !

**Pull request merged**
